### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by Riciko** [jordenhill/Rikaitan#7]
The extension was working up until a few days ago, I have not changed anything with Safari nor the extension. Though, for whatever reason it has ceased to work. 

Is it something on my end or is this a known issue? Sorry for the lack of detail, frankly, I rely on this extension quite a bit living here in Japan and all. 

Furthermore, determining whether or not the app is enabled or not is quite difficult, do you plan on addressing this in the future? 

Thanks for the extension, it's been great up until now, I look forward to utilizing it again in the future.

Safari Version 8.0.2 (10600.2.5)

**Comment by jordenhill** [comment]
It appears there may have been errors with the recent update to the extension causing it to not start. Sorry about that, sometimes the tools for testing Safari extensions can be very buggy and make problems hard to notice and fix until people use it. I've fixed it and put up the new version.

Unfortunately I haven't found any options to make the toolbar icon show that the app is on or off. I'll look into seeing if some kind of workaround is possible.

Thank you for using Rikaitan.

**Comment by Riciko** [comment]
I completely understand, thanks for the fast fix! I look forward to continue using it. 

I'll most definitely recommend this to others.


Cheers from Tokyo~
